name: hamsm_env
channels:
  - conda-forge
  - defaults
dependencies:
 - numpy
 - h5py
 - matplotlib
 - mdtraj
 - pyemma
 - sphinx_rtd_theme
 - flake8
 - Sphinx
 - pytest
 - rich
 - sphinx_rtd_theme
 - tqdm
 - scipy
