# This is a basic workflow to help you get started with Actions

name: Build documentation - cached

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: actions/checkout@v1


    - uses: actions/cache@v2
      id: cache-id
      with:
        path: ${{ runner.temp }}/cache-directory
        key: ${{ runner.os }}-cache-msmwe-env

    # Required action
    - uses: airvzxf/cache-anything-new-action@v1.0.1
      with:
        script: 'setup_environment.sh'
        is_cached: ${{ steps.cache-id.outputs.cache-hit }}
        cache: ${{ runner.temp }}/cache-directory
        snapshot: '/'
        exclude: '/boot /data /dev /mnt /proc /run /sys'

    - name: "Render with sphinx"
      shell: bash -l {0}
      run: "cd docs && sphinx-build -b html . build && cd .. "



    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/jdrusso/msm_we.git --branch gh-pages --single-branch gh-pages
        cp -r docs/build/* gh-pages/
        mkdir -p gh-pages/build
        cp -r docs/build/stubs gh-pages/build
        cd gh-pages
        touch .nojekyll
        mkdir -p build
        cp -r stubs/* build/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git add -f build
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
