name: Run tests via mamba

on:
  push:
    branches:
      - "gh_actions_dev"
      - "main"
  pull_request:
    branches:
      - "main"

# Or top-level:
defaults:
  run:
    shell: bash -l {0}
    
jobs:
  test:
    name: Test on Linux, Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    continue-on-error: true

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
        
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        cache-env: true
        environment-file: environment.yml
        extra-specs: |
          python=${{ matrix.python-version }}


    - name: Install package
      run: |
        conda info --all
        python -m pip install .[tests]
        conda list
    - name: Run tests
      run: |
        pytest -v --color=yes --capture=no --log-cli-level INFO
